### ISSUE TITLE
兄弟，你的本地事务表用错了

### ISSUE THREAD

**Issue by wongben** [mufengCc/transaction-mq#1]
要把insert(本地事务表) + 业务更新放在同一个事务里操作。这样才能利用数据库事务，来保证数据一致性。然后再通过额外投递线程把消息投递出去。

**Comment by mufengCc** [comment]
> 要把insert(本地事务表) + 业务更新放在同一个事务里操作。这样才能利用数据库事务，来保证数据一致性。然后再通过额外投递线程把消息投递出去。

说的有道理。 

将本地消息事务绑定到业务操作事务中，确实比较严谨。  但我这里不考虑由于数据库宕机或新增本地消息表失败这种场景。

如果有更好的实现方案，可以提交个PR，互相学习一下
